import '../models/models.dart';

class MockDataService {
  static final List<FacilityModel> facilities = [
    FacilityModel(
      id: '1',
      name: 'Beşiktaş Belediyesi',
      address: '34353 Beşiktaş/İstanbul',
      type: 'belediye',
      rating: 4.3,
      isOpen: true,
      openHours: '08:00 - 18:00',
      estimatedWaitMinutes: 12,
      departments: [
        DepartmentModel(
          id: 'd1',
          name: 'Vatandaş Hizmetleri',
          facilityId: '1',
          icon: '🏛️',
          currentQueueLength: 8,
          staff: [
            StaffModel(
              id: 's1',
              name: 'Ahmet Yılmaz',
              title: 'Müdür Yardımcısı',
              departmentId: 'd1',
              rating: 4.5,
              currentQueueLength: 5,
              estimatedWaitMinutes: 10,
              isAvailable: true,
            ),
            StaffModel(
              id: 's2',
              name: 'Fatma Kaya',
              title: 'Uzman',
              departmentId: 'd1',
              rating: 4.2,
              currentQueueLength: 3,
              estimatedWaitMinutes: 8,
              isAvailable: true,
            ),
          ],
        ),
        DepartmentModel(
          id: 'd2',
          name: 'Ruhsat İşlemleri',
          facilityId: '1',
          icon: '📄',
          currentQueueLength: 5,
          staff: [
            StaffModel(
              id: 's3',
              name: 'Mehmet Demir',
              title: 'Uzman',
              departmentId: 'd2',
              rating: 4.0,
              currentQueueLength: 5,
              estimatedWaitMinutes: 15,
              isAvailable: false,
            ),
          ],
        ),
      ],
    ),
    FacilityModel(
      id: '2',
      name: 'Ziraat Bankası – Kadıköy',
      address: '34710 Kadıköy/İstanbul',
      type: 'banka',
      rating: 4.1,
      isOpen: true,
      openHours: '09:00 - 17:00',
      estimatedWaitMinutes: 8,
      departments: [
        DepartmentModel(
          id: 'd3',
          name: 'Bireysel İşlemler',
          facilityId: '2',
          icon: '💳',
          currentQueueLength: 12,
          staff: [
            StaffModel(
              id: 's4',
              name: 'Ayşe Çelik',
              title: 'Müşteri Temsilcisi',
              departmentId: 'd3',
              rating: 4.7,
              currentQueueLength: 4,
              estimatedWaitMinutes: 7,
              isAvailable: true,
            ),
          ],
        ),
        DepartmentModel(
          id: 'd4',
          name: 'Kredi İşlemleri',
          facilityId: '2',
          icon: '🏦',
          currentQueueLength: 6,
          staff: [
            StaffModel(
              id: 's5',
              name: 'Ali Öztürk',
              title: 'Kredi Uzmanı',
              departmentId: 'd4',
              rating: 4.4,
              currentQueueLength: 6,
              estimatedWaitMinutes: 20,
              isAvailable: true,
            ),
          ],
        ),
      ],
    ),
    FacilityModel(
      id: '3',
      name: 'Şişli PTT Şubesi',
      address: '34381 Şişli/İstanbul',
      type: 'ptt',
      rating: 3.9,
      isOpen: false,
      openHours: '08:30 - 17:30',
      estimatedWaitMinutes: 20,
      departments: [
        DepartmentModel(
          id: 'd5',
          name: 'Kargo Teslim',
          facilityId: '3',
          icon: '📦',
          currentQueueLength: 0,
          staff: [],
        ),
        DepartmentModel(
          id: 'd6',
          name: 'Fatura & Ödemeler',
          facilityId: '3',
          icon: '💰',
          currentQueueLength: 0,
          staff: [],
        ),
      ],
    ),
    FacilityModel(
      id: '4',
      name: 'Ataşehir 1. Noteri',
      address: '34758 Ataşehir/İstanbul',
      type: 'noter',
      rating: 4.6,
      isOpen: true,
      openHours: '09:00 - 18:00',
      estimatedWaitMinutes: 25,
      departments: [
        DepartmentModel(
          id: 'd7',
          name: 'Tapu İşlemleri',
          facilityId: '4',
          icon: '🏠',
          currentQueueLength: 9,
          staff: [
            StaffModel(
              id: 's6',
              name: 'Selin Arslan',
              title: 'Noter Yardımcısı',
              departmentId: 'd7',
              rating: 4.8,
              currentQueueLength: 9,
              estimatedWaitMinutes: 25,
              isAvailable: true,
            ),
          ],
        ),
      ],
    ),
  ];

  static List<NotificationModel> get notifications => [
        NotificationModel(
          id: 'n1',
          title: 'Sıranız Yaklaşıyor',
          message: 'Beşiktaş Belediyesi\'nde 3. sıradasınız. Lütfen hazır olun.',
          type: 'queue',
          time: DateTime.now().subtract(const Duration(minutes: 5)),
          isRead: false,
        ),
        NotificationModel(
          id: 'n2',
          title: 'Doktordan Yeni Mesaj',
          message: '"Önceki randevunuz başarıyla sonuçlandı. İyi günler dileriz."',
          type: 'message',
          time: DateTime.now().subtract(const Duration(minutes: 12)),
          isRead: false,
        ),
        NotificationModel(
          id: 'n3',
          title: 'Randevu Onaylandı',
          message: 'Ziraat Bankası – Kadıköy randevunuz başarıyla oluşturuldu.',
          type: 'appointment',
          time: DateTime.now().subtract(const Duration(hours: 1)),
          isRead: true,
        ),
        NotificationModel(
          id: 'n4',
          title: 'Kayıt Tamamlandı',
          message: 'Profiliniz başarıyla güncellendi.',
          type: 'update',
          time: DateTime.now().subtract(const Duration(hours: 3)),
          isRead: true,
        ),
        NotificationModel(
          id: 'n5',
          title: 'Check-In Tamamlandı',
          message: 'Ataşehir 1. Noteri\'ne giriş yaptınız.',
          type: 'queue',
          time: DateTime.now().subtract(const Duration(hours: 5)),
          isRead: true,
        ),
      ];
}
